import React from 'react';
import { motion } from 'framer-motion';

export default function Terms() {
    return (
        <div className="bg-white min-h-screen pt-32 pb-20">
            <div className="max-w-3xl mx-auto px-6">
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mb-16"
                >
                    <h1 className="text-4xl font-black text-slate-900 tracking-tighter mb-4 uppercase italic">
                        Terms & <span className="text-premium">Conditions</span>
                    </h1>
                    <p className="text-slate-500 font-bold uppercase tracking-widest text-xs">Last Updated: April 2026</p>
                </motion.div>

                <div className="prose prose-slate max-w-none space-y-10 text-slate-600 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
                        <p>By accessing or using the EquiSense platform, you agree to be bound by these Terms and Conditions. Our services are provided for informational and research purposes only and do not constitute financial advice.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">2. Subscription & Access</h2>
                        <p>Institutional features and AI-driven insights are available to registered and subscribed users. You are responsible for maintaining the confidentiality of your account credentials.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">3. No Investment Advice</h2>
                        <p>EquiSense is a quantitative research terminal. All predictions, strategies, and signals generated by our AI models are based on historical data and mathematical probabilities. Past performance is not indicative of future results. Trading in securities markets involves high risk.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">4. Intellectual Property</h2>
                        <p>All proprietary algorithms, UI designs, and analysis methodologies are the intellectual property of EquiSense Platforms Pvt Ltd. Unauthorized reproduction or commercial use is strictly prohibited.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">5. Limitation of Liability</h2>
                        <p>EquiSense shall not be liable for any financial losses incurred through the use of our platform. Users are encouraged to perform their own due diligence or consult with a SEBI-registered advisor before making investment decisions.</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
